### ISSUE TITLE
Forest Classifier

### ISSUE THREAD

**Issue by crflynn** [crflynn/skgrf#42]
Probability forest implemented but not yet released in grf

**Comment by crflynn** [comment]
@erikcs Do you have an ETA on a new release?

**Comment by erikcs** [comment]
Hopefully by the end of this month (July at the latest). The final release addition is https://github.com/grf-labs/grf/pull/988, and after that we will prepare a CRAN release.

**Comment by erikcs** [comment]
Hi @crflynn, the [2.0 release](https://grf-labs.github.io/grf/CHANGELOG.html#200---2021-06-22) is out now, and as you see there are a few breaking changes. From the wrapper side the `orthog.boosting` argument is removed from `causal_forest`, and explicit support for sparse training data is removed (the data class is now concrete). 

We haven't documented all the C++ changes since we strictly speaking only follow Semantic Versioning for the R package, however considering we don't want to cause trouble for repos like this which maintains wrappers - the most prominent internal changes are just removing sparse data support and using some Eigen arrays instead of std::vectors in internals, I don't think wrappers should be much affected by this release.

**Comment by crflynn** [comment]
Thanks for the heads up. I quickly tested 2.0 and the bindings compiled just fine without any code change. It looks like most of the big changes are on the R side so it should be relatively painless here.
